---
title: "mapper_examples"
output: html_document
date: "2024-01-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(usedist)
library(igraph)
library(RCy3)
source("R/1D_mapper_viz.R")
source("R/ballmapper_viz.R")
source("R/combomapper_viz.R")
```

## Noisy Circle

```{r, echo=FALSE}
# make sure cytoscape is open and running!
circle.data = data.frame( x= sapply(1:1000, function(x) cos(x)) + rnorm(100, 500, .03), y = sapply(1:1000, function(x) sin(x)) + rnorm(100, 0, 0.03))
circle.dist = dist(circle.data)

plot(circle.data$x, circle.data$y, pch=20)
# cyballmapper(circle.data, circle.dist, .5)
cymapper(circle.data, circle.data$x, circle.dist, 10, 15, "single")
```

## Noisy Clover

```{r, echo=FALSE}
clover.data = data.frame( x= sapply(1:1000, function(x) cos(x)*sin(2*x)) + rnorm(100, 500, .03), y = sapply(1:1000, function(x) sin(2*x)*sin(x)) + rnorm(100, 0, 0.03))
clover.dist = dist(clover.data)

plot(clover.data$x, clover.data$y, pch=20)
# cyballmapper(clover.data, clover.dist, .5)
cymapper(clover.data, clover.data$x, clover.dist, 5, 15, "single")
```

## Car Data
```{r, echo=FALSE}
car_data = mtcars
car_data.dists = dist(car_data, method = "max")
cymapper(car_data, car_data$qsec, car_data.dists, 5, 40, "single")
```

## flares
```{r, echo=FALSE}
# create data set with 7 flares.

flare.data = data.frame(x = c(runif(200, -30,30), runif(200, -6,30), runif(200, -6,-5), runif(200, 5,6), runif(200, -6,6)), y = c(runif(200, 5,6), runif(200, -6,-5), runif(200, -20,20), runif(200, -20,20), runif(200, -6,6)))

plot(flare.data$x, flare.data$y, pch=20)
cymapper(flare.data, flare.data$x, dist(flare.data), 10, 20, "single")
# cyballmapper(flare.data, dist(flare.data), 3)
```

